### ISSUE TITLE
Lookup words in Forth standard

### ISSUE THREAD

**Issue by ellerh** [larsbrinkhoff/forth-mode#10]
Maybe you can add a command to browse the description of a word in the Forth standard
like this one:
https://github.com/ellerh/dpans.el/blob/master/dpans.el

**Comment by larsbrinkhoff** [comment]
Yes, that's a good idea!

**Comment by Reepca** [comment]
I'm reminded of SLIME's C-c C-d h, which I've used a lot! I second (third?) the idea.

**Comment by larsbrinkhoff** [comment]
Fixed by #39.
