### ISSUE TITLE
Terminal escape sequences

### ISSUE THREAD

**Issue by ellerh** [larsbrinkhoff/forth-mode#14]
SwiftForth emits, e.g. when using `see`, the escape sequence `^[[6n` and then waits. Apparently `CSI 6n` tells the terminal emulator to report the cursor position.  I don't know how to disable this on the SwiftForth side, so maybe Emacs should handle a few of the standard escape sequences.  This might also allow us to introduce some custom escape sequences for the communcation with the subprocess.

**Comment by larsbrinkhoff** [comment]
Right, I already added code to filter out escape sequences, in `forth-scrub`.

Just one suggestion: Did you try `TERM=dumb`?

**Comment by ellerh** [comment]
> Just one suggestion: Did you try TERM=dumb?

Yes. Same problem.
I also tried to connect SwiftForth with a pipe instead of a pty (process-connection-type = nil) but then SwiftForth doesn't print the normal prompt and exits after the second error.

**Comment by larsbrinkhoff** [comment]
The cursor position query can be turned off with

    : foo 0 0 ;
    ' foo 'get-xy !

Perhaps a SwiftForth backend should set up a *Device Personality* that disables all uses of terminal escape sequences.

**Comment by ellerh** [comment]
> The cursor position query can be turned off with
> `:noname 0 0 ; 'get-xy !`

Indeed.

> Perhaps a SwiftForth backend should set up a Device Personality that disables all uses of terminal escape sequences.

Yes, sounds reasonable.

**Comment by larsbrinkhoff** [comment]
There is now a file called `backend/swiftforth.el` where this could be done.

**Comment by larsbrinkhoff** [comment]
I believe this is fixed?
