### ISSUE TITLE
Add imenu support

### ISSUE THREAD

**Issue by lokedhs** [larsbrinkhoff/forth-mode#2]
In order to add imenu support, all that needs to be done is to set `imenu-generic-expression` to a set of matchers that are able to detect the form of a function definition.

Once that has been written, adding the following will use this to provide speedbar support:

```
(with-eval-after-load 'speedbar
  (speedbar-add-supported-extension ".fs"))
```

**Comment by larsbrinkhoff** [comment]
Thanks!  I already have this:  
https://github.com/larsbrinkhoff/forth-mode/blob/cdab2e4ec1e40f3395938c1a258a8bd525b2fc8d/forth-mode.el#L90-L96

**Comment by larsbrinkhoff** [comment]
Elisp ref:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Imenu.html

How do I get information out of `imenu`?

**Comment by lokedhs** [comment]
You can use `(imenu--make-index-alist t)` to get imenu entries for the file.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by larsbrinkhoff** [comment]
I added the speedbar thing, but I'm not sure it works.
