### ISSUE TITLE
Terminal device personality reset

### ISSUE THREAD

**Issue by ellerh** [larsbrinkhoff/forth-mode#28]
SwiftForth seems to reset the device personality on errors:

```
SwiftForth i386-Linux 3.6.3 29-Jun-2016 
'personality @ . 134554011  ok
include swiftforth.fth  ok                                                     
'personality @ . 134756820  ok
abort 
'personality @ . 134554011  ok
```

**Comment by larsbrinkhoff** [comment]
The SwiftForth distribution file `lilb/samples/win32/serial.f` says:

> quit is necessary in both cases to reset the catch frame which maintains the default personality for restoring on throws.

So supposedly, there is a top-level `CATCH` which changes the personality when an exception is thrown.  The options would be:
- Have another `CATCH` which overrides the system `CATCH`.
- Find out where the default personality is stored, and change that.

**Comment by ellerh** [comment]
> Find out where the default personality is stored, and change that.

Here's an interesting observation about QUIT:
```
SwiftForth i386-Linux 3.6.3 29-Jun-2016 
'personality @ . 134554011  ok                                                 
include swiftforth.fth  ok                                                     
'personality @ . 134756820  ok
quit 'personality @ . 134756820  ok
abort 
'personality @ . 134756820  ok
```
Maybe QUIT also overwrites the default personality.

**Comment by ellerh** [comment]
Disassembling QUIT reveals a call to /INTERPRET.  My guess is that this initializes something important.
I tried it out with 6b74225.  We will see how it works.
