### ISSUE TITLE
pushnew doesn't exist in freshly installed emacs

### ISSUE THREAD

**Issue by vigilancetech-com** [larsbrinkhoff/forth-mode#67]
In the installation instructions when it says:

(pushnew "DIR" load-path)
(require 'forth-mode)
(require 'forth-block-mode)
(require 'forth-interaction-mode)

I get an error about pushnew not existing in a fresh emacs installation.   cl-pushnew does appear to exist however.

**Comment by larsbrinkhoff** [comment]
Thanks!  I fixed the instructions to use `add-to-list` instead.
