### ISSUE TITLE
wrong type argument stringp nill error with forth-load-file under mingw32 (msys2) and lbforth

### ISSUE THREAD

**Issue by vigilancetech-com** [larsbrinkhoff/forth-mode#69]
1. from within (spac)emacs I load up a file in the lbforth home directory (e.g. INSTALL).

1. I then load up lib/bench.fth.

1. I execute run-forth (M-x run-forth, or SPC SPC run-forth)

1. tell it I want to use lbforth ("forth" executable)

1. I verify its running by typing "words" 

1. I switch back to bench.fth with C-x o

1. I do C-c C-l to "load" the current buffer into forth.

1. I get this stack trace in the debugger:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("[?[0-9;]*[a-z]" nil 0)
  forth-scrub(nil t)
  forth-load-file("c:/msys64/home/kevin/0work/lbForth/lib/bench.fth")
  funcall-interactively(forth-load-file "c:/msys64/home/kevin/0work/lbForth/lib/bench.fth")
  call-interactively(forth-load-file nil nil)
  command-execute(forth-load-file)

And this message from windows:

![image](https://cloud.githubusercontent.com/assets/20651234/25766328/bc6dae5c-31a6-11e7-8d4c-919a7e63388e.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm ranger auto-completion better-defaults themes-megapack emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by vigilancetech-com** [comment]
I'm thinking this might be more to do with benchmark rather than forth-mode.   I tried loading other files and it worked.   Its just benchmark was the first.   So this probably needs to be reported in lbforth rather than here.

**Comment by larsbrinkhoff** [comment]
Thanks!

I'll look into bench.fth. I haven't used it in a while so maybe it has rotted.

**Comment by larsbrinkhoff** [comment]
Note that bench.fth uses lib/elapsed.fth to measure time.  That library file only words in Linux/x86.

**Comment by larsbrinkhoff** [comment]
Part of the problem may be that you started lbForth from the lib/bench.fth buffer.  That made lbForth run from the lib directory.

bench.fth first includes lib/elapsed.fth, which words if lbForth has been installed.  It can find its library files.

Then it tries to include files in the contrib directory.  Those files can only be found if the current directory is the top-level lbForth source code repository.
