### ISSUE TITLE
Input gets echoed three times

### ISSUE THREAD

**Issue by Reepca** [larsbrinkhoff/forth-mode#74]
If I start a fresh gforth session with M-x run-forth and type `2 RET`, the buffer then looks like this:

    Gforth 0.7.9_20180726, Copyright (C) 1995-2017 Free Software Foundation, Inc.
    Gforth comes with ABSOLUTELY NO WARRANTY; for details type `license'
    Type `help' for basic help
    2
    22  ok

It had been echoing twice for awhile - not too terrible, at least it's not asymmetric. For what it's worth, I'm using emacs 26.1 and the latest gforth git checkout. forth-mode installed from MELPA.

**Comment by jpellegrini** [comment]
I can't reproducee this with the latest MELPA version (`20170527.1930`) and gforth `0.7.9_20181122`. Can you try again?  By the way, I have done some enhancements, if you're interested -- see [here](https://github.com/jpellegrini/forth-mode) (I have made pull requests)

**Comment by Reepca** [comment]
Ah, sorry I forgot to follow up on this. It got fixed in gforth (https://lists.gnu.org/archive/html/gforth/2018-07/msg00020.html). Will close this now.

And good to see you working on this! Currently I'm using the forth mode bundled with gforth, but I'm still excited to see progress on this.
