### ISSUE TITLE
Deprecation of `cl`

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [larsbrinkhoff/forth-mode#91]
Emacs `28.2` shows warnings for packages depending on `cl`, since `cl` has been deprecated. According to other threads, for example https://github.com/kiwanami/emacs-epc/issues/35 the replacement is `cl-lib`.

Would it be feasible to make the switch to avoid the deprecation warnings and possible later breakage of forth-mode?

**Comment by larsbrinkhoff** [comment]
Yes, it would be feasible.

**Comment by phikal** [comment]
I guess this can be closed now?

**Comment by ZelphirKaltstahl** [comment]
I guess so. Closing now.
